# Generated by Django 3.1.4 on 2020-12-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.rating'),
        ),
    ]
