# Generated by Django 3.1.4 on 2020-12-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201226_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
